Add job for following build status in CICD pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,4 +38,21 @@ jobs:
             --deployment-group-name frontend-deployer-group \
             --deployment-config-name CodeDeployDefault.OneAtATime \
             --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
+      - name: Deployment status
+        id: status
+        run: |
+          sleep 90
+          status=`aws deploy get-deployment \
+            --deployment-id "$( aws deploy list-deployments \
+              --application-name user-api-deployer \
+              --deployment-group-name frontend-deployer-group \
+              --query 'deployments' \
+              --max-items 1 \
+            | grep -oP '"\K[^"\047]+(?=["\047])')" \
+            --query "deploymentInfo.[status]" | grep -oP '"\K[^"\047]+(?=["\047])'`
+          sleep 2
+          if [ "$status" != "Succeeded" ]; then
+            echo "::error::Deployment unsuccesful, status $status"
+            exit 1
+          fi
 
